### ISSUE TITLE
轉換到/從日本語新字體、舊字體失敗

### ISSUE THREAD

**Issue by BSBMteam** [CXuesong/OpenCCSharp#3]
使用了下面的測試文字：
`韋伯的任務是尋找最早、最遙遠的恆星和星系，這些恆星和星系出現在137億年前，從宇宙大爆炸（發生在138億年前）後的塵霧中誕生。`

不管是Hans、Hant、HK、TW（Shinjitai、Kyujitai之外的所有選項），轉換到Kyujitai、Shinjitai失敗，有下面的信息：

```
转换失败

Error: 指定的转换对不受支持：Hant -> Kyujitai。 at i (https://cxuesong.github.io/OpenCCSharp.WebApp/15.index.js:1:515) at async https://cxuesong.github.io/OpenCCSharp.WebApp/index.js:1:149502
```

從Kyujitai、Shinjitai轉換到Hans、Hant、HK、TW（Shinjitai、Kyujitai之外的所有選項）時，顯示下面的：

```
转换失败

Error: 指定的转换对不受支持：Kyujitai -> Hans。 at i (https://cxuesong.github.io/OpenCCSharp.WebApp/15.index.js:1:515) at async https://cxuesong.github.io/OpenCCSharp.WebApp/index.js:1:149502
```

**Comment by BSBMteam** [comment]
搬到 https://github.com/CXuesong/OpenCCSharp.WebApp/issues/2
